version: 2

models:
  - name: my_first_dbt_model
    description: "Starter model"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "Second starter model"
    columns:
      - name: id
        tests:
          - unique
          - not_null